"""adding more columns

Revision ID: 00e0e2af63a3
Revises: 3849b45c40fd
Create Date: 2025-09-30 01:17:17.750150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e0e2af63a3'
down_revision: Union[str, None] = '3849b45c40fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
